from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils import timezone
class User(AbstractUser):
    """
    PK: id (auto-generated by Django)

    User Roles:
    - Student
    - Instructor
    - Administrator
    """

    ROLE_CHOICES = [
        ('student', 'Student'),
        ('instructor', 'Instructor')
    ]

    # User role in the system
    role = models.CharField(max_length=20, choices=ROLE_CHOICES, default='student')

    # Account creation date
    registration_date = models.DateTimeField(default=timezone.now)

    # Last login time
    last_login = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return self.username

