# Generated by Django 5.2.8 on 2025-12-17 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_bio_user_profile_picture_user_website_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='website',
        ),
    ]
